name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy ruff

    - name: Check formatting with black
      run: black . --check --diff

    - name: Check imports with isort
      run: isort . --check-only --diff --profile black

    - name: Type checking with mypy
      run: mypy .

    - name: Lint with ruff
      run: ruff check . --format=github

    - name: Check for security issues with bandit
      run: |
        pip install bandit
        bandit -r . -ll